### ISSUE TITLE
Weird symbols in output

### ISSUE THREAD

**Issue by PikachuPlays07** [Siddharth3141/Hypixel_Skyblock_Auction_Flipper#2]
![image](https://user-images.githubusercontent.com/83122770/128636840-f10f081e-1f89-424e-a180-d9bdbdd5c6d8.png)

In the output, there are characters surrounding the name, prices and profit (margin)

All dependencies installed

**Comment by Overthrowing** [comment]
I believe this is due to colorama not working properly on some operating systems, can you tell me what os you are using?

**Comment by PikachuPlays07** [comment]
Windows 10

**Comment by Overthrowing** [comment]
Ok, I figured it out! I had forgotten to initialize colorama which caused it to not work in some terminals. I made a commit that should hopefully fix the issue, let me know if it works.

**Comment by PikachuPlays07** [comment]
![image](https://user-images.githubusercontent.com/83122770/129018174-67bbcb29-faac-4174-9bc0-52a1b407335f.png)
It now works if I run it as a py.exe but in the shell it's still not fixed

**Comment by Overthrowing** [comment]
That's odd, it works fine in cmd, Powershell, and PyCharm for me. (The dungeon star characters don't show up in some terminals but otherwise it seems fine)

**Comment by FoxNerdSaysMoo** [comment]
It's most likely that the terminal in use doesn't support colors; but I can draft a version with a config option to disable colors.

**Comment by FoxNerdSaysMoo** [comment]
#3

**Comment by Overthrowing** [comment]
This should resolve the issue.
