### ISSUE TITLE
Recommended Params and more to add

### ISSUE THREAD

**Issue by ghost** [Siddharth3141/Hypixel_Skyblock_Auction_Flipper#5]
What params do you recommend to filter through the junk like Decoys?

Could you also make a tool bar in the future like https://sky.coflnet.com/ 's item finder which allows you to add certain filters such as star lvl, certain enchantments, hpb, recomb, etc. That'd improve the bot speed for it'll allow for more direct and therefore faster performance because it will have less items to query through.

Thanks,
VD

**Comment by Overthrowing** [comment]
I would add a minimum price for items and I'm not really actively developing this right now but I will try to make a GUI in the future when I find the time.
